--■ 기타사항
--## 오라클 서비스가 정상 구동 중인지 확인하기
-- ### 1. services.msc 켜기
-- ### 2. Oracle ~ TNSListener 항목을 찾는다.
-- 이는 다른 곳에서 Oracle DB로 접속할 수 있음.
-- 이 Listener가 꺼져있으면 자신의 컴퓨터인 sqlPlus에서만 접속이 가능하다
-- ### 3. oracleServiceXE 서비스가 꺼져 있으면 DB가 구동되지 않는다.
-- 진짜 DB프로그램이므로 항상 켜져 있어야 한다.

--## 데이터베이스의 물리적인 공간 확인하기
--드라이브명:\app\사용자명\product\18.0.0\oradata\XE
--### USERS01.DBF는 users의 물리적인 이름을 의미한다.
--### SYSTEM01.DBF는 system의 물리적인 이름을 의미한다.
--위의 물리적인 공간이 손상되면 오라클 데이터베이스가 정상적으로 구동되지 않는다.
--### TEMP01.DBF TEMPORARY 영역의 물리적인 이름을 의미한다.

--## 오라클 JDBC사용을 위한 jar파일
--### 드라이브명:\app\사용자명\product\18.0.0\dbhomeXE\jdbc\lib\ojdbc8.jar
-- JAVA로 만들어진 프로그램에서 oracle db에 접속하기 위해 필요한 전용 드라이버 (.jar)


--## 오라클 리스너 파일 설정하기
--### 드라이브명:\app\사용자명\product\18.0.0\dbhomeXE\network\admin\\listener.ora
--SID_LIST_LISTENER =
--  (SID_LIST =
--    (SID_DESC =
--      (SID_NAME = CLRExtProc)
--      (ORACLE_HOME = C:\app\sist\product\18.0.0\dbhomeXE)
--      (PROGRAM = extproc)
--      (ENVS = "EXTPROC_DLLS=ONLY:C:\app\sist\product\18.0.0\dbhomeXE\bin\oraclr18.dll")
--    )
--  )

--LISTENER =
--  (DESCRIPTION_LIST =
--    (DESCRIPTION =
--      (ADDRESS = (PROTOCOL = TCP)(HOST = 컴퓨터이름 또는 127.0.0.1 또는 아이피주소)(PORT = 1521))
--      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
--    )
--  )

--## 클라이언트가 접속할 때 필요한 환경설정
--서버의 아이피, 포트번호와 함께 SERVICE_NAME(SID)을 알고 있어야 한다.
--추가적으로 사용자이름과 비밀번호를 알고 있어야 함.
--### 드라이브명:\app\사용자명\product\18.0.0\dbhomeXE\network\admin\\tnsnames.ora
--# tnsnames.ora Network Configuration File: C:\app\sist\product\18.0.0\dbhomeXE\NETWORK\ADMIN\tnsnames.ora
--# Generated by Oracle configuration tools.
--# 컴퓨터이름(DESKTOP-********)
--XE =
--  (DESCRIPTION =
--    (ADDRESS = (PROTOCOL = TCP)(HOST = 컴퓨터이름 또는 127.0.0.1 또는 아이피주소)(PORT = 1521))
--    (CONNECT_DATA =
--      (SERVER = DEDICATED)
--      (SERVICE_NAME = XE)
--    )
--  )
--
--LISTENER_XE =
--  (ADDRESS = (PROTOCOL = TCP)(HOST = 컴퓨터이름 또는 127.0.0.1 또는 아이피주소)(PORT = 1521))
--
--
--ORACLR_CONNECTION_DATA =
--  (DESCRIPTION =
--    (ADDRESS_LIST =
--      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
--    )
--    (CONNECT_DATA =
--      (SID = CLRExtProc)
--      (PRESENTATION = RO)
--    )
--  )
--외부에서 접속하기 위해서는 방화벽에서 1521(inbound)번 포트를 예외로 등록해 주어야 한다.

-- ※ 데이터 링크
--   ο 데이터 링크 설정
---------------------------------------------------------
-- 사용 예
-- 데이터 링크 설정 형식

    --단 관리자 계정에서 다음의 권한을 지정해야 한다.
    GRANT CREATE DATABASE LINK TO sky;
    
    --링크 설정 형식 예제
    CREATE DATABASE LINK dblink
    CONNECT TO user IDENTIFIED BY password
    USING 
    '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)
    (HOST=아이피주소)(PORT=1521))
    (CONNECT_DATA=(SERVICE_NAME=db_sid)))';

    --링크 설정하기
    CREATE DATABASE LINK link_test
        CONNECT TO sky IDENTIFIED BY "java$!"
        USING 
        '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)
        (HOST=211.238.142.49)(PORT=1521))
        (CONNECT_DATA=(SERVICE_NAME=XE)))';

    SELECT * FROM emp UNION ALL -- 자신의 호스트에 존재하는 테이블
    SELECT * FROM emp@link_test; --연결된 211.238.142.49의 sky계정에 있는 테이블 정보를 가져온다
    SELECT * FROM tab@link_test;
    
    SELECT * FROM user_db_links;
    
    --링크 삭제
    DROP DATABASE LINK link_test;

-- ※ 논리적인 백업
--   ο EXPORT 및 IMPORT 예
-- EXPORT: 데이터베이스 내 테이블 및 프로시저 등을 dmp파일로 압축 (논리적으로 백업)
    cmd> exp userid=sky/"java$!" file='c:\data\sky.dmp' owner=sky
    select * from tab;
    --테이블 삭제
    
    DROP TABLE emp_score PURGE;
    DROP TABLE emp PURGE;
-- IMPORT: 데이터베이스 내부로 테이블 및 프로시저 등 export했던 압축파일을 가져오기
--  논리적으로 복원
    cmd> imp userid=sky/"java$!" file='c:\data\sky.dmp' fromuser=sky touser=sky

select * from tab;